### ISSUE TITLE
building

### ISSUE THREAD

**Issue by ghost** [icon-project/java-score-examples#12]
Anyone seen this?

      > No matching variant of foundation.icon:gradle-javaee-plugin:0.8.1 was found. The consumer was configured to find a runtime of a component compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability foundation.icon:gradle-javaee-plugin:0.8.1 declares a component, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability foundation.icon:gradle-javaee-plugin:0.8.1 declares a runtime of a component, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

**Comment by sink772** [comment]
Your project needs to be declared to use Java 11.
```
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
```
