### ISSUE TITLE
How to call integration tests ?

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/java-score-examples#9]
Hi,
I haven't found a gradle task or any documentation about how to call the integration tests such these ones : https://github.com/icon-project/java-score-examples/tree/master/multisig-wallet/src/intTest/java/foundation/icon/test
Would you have any direction about how to do that please ?

Thank you 👍

**Comment by sink772** [comment]
I've updated README.md to elaborate the usage of integration testing.
https://github.com/icon-project/java-score-examples#integration-testing

Also you can verify where the integration tests are:
```
$ ./gradlew tasks --all | grep integrationTest
irc3-token:integrationTest - Runs integration tests.
multisig-wallet:integrationTest - Runs integration tests.
sample-crowdsale:integrationTest - Runs integration tests.
```

**Comment by ICONationDevTeam** [comment]
Thank you very much 🙏
